[package]
name = "factorygame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = { version= "0.12.1", features = ["texture_to_file"]}
